version: '2'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: postgres
      POSTGRES_DB: econnify
    ports:
      - '5432:5432'
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/init.sql